version: "2"
services:
  web:
    container_name: nginx-alpine
    image: nginx:alpine
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "8080:80"
      # - "8443:443"
    volumes:
      - ${WEB_ROOT}:/var/www
      - ${BOOKS_DIR}:/books
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/conf.d:/etc/nginx/conf.d:ro
      - ./config/custom_conf:/config
    depends_on:
      - "php"
    networks:
      - nginxnet
  php:
    container_name: php-fpm-alpine
    image: mousi/php:fpm-alpine-gd
    environment: 
      - TZ=${TIMEZONE}
    volumes:
      - ${WEB_ROOT}:/var/www
      - ${BOOKS_DIR}:/books
    networks:
      - nginxnet
networks:
  nginxnet:
    external:
      name: ${DOCKER_NETWORK}
